// The roster: every character in Chicken Cross, one line each, grouped into
// collections. The line format is described above parseLine() in
// js/roster.js; in short:
//
//   "Name | plan | colour=hex ... hat=kind[:hex] neck= face= back= mark= fx= voice= theme= r=rarity unlock"
//
// All names and designs are original to Chicken Cross.
"use strict";

const COLLECTIONS = [
  { id: "founding", name: "Founding Flock", emoji: "🐔", unlock: "founding",
    blurb: "The twelve birds who crossed the very first road.",
    chars: [
      "Chicken | chicken | f=🐔 id=hen",
      "Rooster | rooster | f=🐓 id=rooster",
      "Chick | chick | f=🐤 id=chick",
      "Hatchling | chick | f=🐥 id=hatchling",
      "Duck | duck | f=🦆 id=duck",
      "Penguin | penguin | f=🐧 id=penguin",
      "Owl | owl | f=🦉 id=owl",
      "Flamingo | flamingo | f=🦩 id=flamingo",
      "Parrot | parrot | f=🦜 id=parrot",
      "Peacock | peacock | f=🦚 id=peacock",
      "Swan | swan | f=🦢 id=swan",
      "Dove | dove | f=🕊️ id=dove",
    ] },

  /* ============================================ the Prize Machine (290) */

  { id: "farmyard", name: "Farmyard Friends", emoji: "🚜",
    blurb: "Mud, hay and an early start.",
    chars: [
      "Tilly Truffle | pig | mark=spots:c9707f",
      "Sir Oinksalot | pig | body=f2b3a0 hat=tophat:3a3a44 neck=bowtie:d33a3a r=2",
      "Mudpuddle Maisie | pig | body=d99a7e snout=c8826a mark=patch:8a5a3c fx=drops",
      "Daisy Buttercup | cow | hat=flower:ffd23f",
      "Clover Moo | cow | patch=8a5a3c muzzle=f7c8b8 neck=bell",
      "Bramble Bull | cow | body=6a4a3a patch=3a2a24 horn=fff4d6 muzzle=c89a8a r=1",
      "Woolly Winifred | sheep | neck=scarf:e05a8a",
      "Dusty Fleece | sheep | body=e8dcc8 skin=6a4a3a",
      "Midnight Merino | sheep | body=4a4a58 skin=1d1d24 r=1",
      "Parsnip | bunny | body=e8e0d8 hat=straw:e05a8a",
      "Hay Bale Hattie | pony | body=d8a86a mane=f4e0b0 hat=straw:d33a3a",
      "Gravel Gertie | chicken | body=c98a4a mark=speckle:7a4a2a",
      "Farmer Fenwick | person | body=6a9a3a pants=3a5a8a hat=straw:6a9a3a hair=8a5a3a",
      "Tractor Tess | person | body=d9412e pants=3a4a6a hat=cap:d9412e form=braid hair=c8783a skin=e8b890",
      "Old Mac Rooster | rooster | body=c86a3a tail=2a4a2a hat=straw:3a7ad9 r=2",
    ] },

  { id: "woodland", name: "Woodland Wanderers", emoji: "🌲",
    blurb: "Rustlers of leaves and keepers of acorns.",
    chars: [
      "Fern Foxglove | fox |",
      "Russet Rascal | fox | body=c8582a neck=bandana:3a7ad9",
      "Silver Brush | fox | body=b8c0c8 socks=5a5a66 r=2",
      "Bramble Bear | bear |",
      "Honeypot Hugo | bear | body=d99a4a muzzle=f4dcb0 neck=scarf:d33a3a",
      "Moss Grizzle | bear | body=6a5a4a muzzle=b8a080 hat=sprout",
      "Prickles | hedgehog |",
      "Conker Quill | hedgehog | body=5a3a2a skin=f0dcc0 hat=cap:3a8a3a",
      "Acorn Ada | mouse | body=a8805a inner=ffc0c8 hat=beret:6a9a3a",
      "Hazel Hoard | mouse | body=c8a078 back=backpack:d98e32",
      "Tawny Hoot | owl | body=b07a4a disc=f0dcc0 hat=laurel",
      "Barnaby Barn Owl | owl | body=e8c890 disc=ffffff tufts=d8b070 r=1",
      "Pip Woodpecker | parrot | body=2a2a30 wing=f4f4f4 tuft=d33a3a tail=2a2a30 beak=6a6a70 legs=6a6a70",
      "Fawn Hollow | pony | body=c8905a mane=8a5a3a mark=spots:f4e8d8",
      "Toadstool Tim | frog | body=8a6a4a belly=d8c8a0 hat=beret:d33a3a",
    ] },

  { id: "pond", name: "Pond & River", emoji: "🐸",
    blurb: "Paddlers, dabblers and one very slow swimmer.",
    chars: [
      "Lily Leapwell | frog | hat=flower:ff9ec4",
      "Bogsworth | frog | body=4a7a3a belly=a8c878 face=monocle",
      "Tadpole Tom | frog | body=3a5a3a belly=8aa878 fx=bubbles",
      "Marsh Mallow | duck | body=c8b8a0 head=f4f0e8 ring=e8c8a0",
      "Dabbler Dot | duck | head=3a5ad9 body=6a6a70",
      "Paddles | duck | body=f6d43a head=f6d43a ring=f6d43a beak=f28c28 fx=bubbles voice=squeak",
      "Grace Glide | swan | hat=tiara:e84a8a",
      "Nocturne | swan | body=2a2a30 beak=d33a3a mask=1d1d24 r=2",
      "Shelly Slowtide | turtle |",
      "Mossback | turtle | shell=5a6a3a plate=8a9a5a hat=sprout",
      "Reed Runner | lizard | body=6aa04a belly=d0e8a0",
      "Kingfisher Kit | parrot | body=2a8ad9 wing=1a6ab0 tuft=2a8ad9 tail=1a5a9a beak=2a2a30 mark=belly:f08a3a",
      "Crayfish Cal | crab | body=a8503a belly=d88a6a",
      "Harriet Heron | flamingo | body=b8c0c8 head=e8ecf0 wing=8a929a legs=d8c070 beak=e8c040 beakTip=d8a030",
    ] },

  { id: "pets", name: "Pet Parade", emoji: "🐾",
    blurb: "Everyone's best friend, and a goldfish.",
    chars: [
      "Whiskers McPurr | cat |",
      "Marmalade | cat | mark=stripes:c8702a",
      "Inky | cat | body=2a2a30 inner=d88aa0 neck=collar:d33a3a",
      "Snowdrop | cat | body=f4f4f4 inner=ffb6c8 neck=bell",
      "Biscuit | dog |",
      "Pepper Pup | dog | body=f4f0e8 ear=2a2a30 muzzle=ffffff mark=spots:2a2a30",
      "Sir Waggington | dog | body=6a4a3a ear=3a2a1a muzzle=c8a078 hat=tophat:2a2a30 neck=bowtie:3a3a44 r=2",
      "Nibbles | mouse |",
      "Hamish Hamster | mouse | body=e8a860 inner=f4c8a0 tail=f4c8a0",
      "Goldie | fish | body=f6a52a fin=f67a2a",
      "Bubbles McFin | fish | body=6ab0e8 fin=3a7ad9 belly=e8f4ff fx=bubbles",
      "Polly Perch | parrot | body=5ac04a wing=f6d43a tuft=f6d43a tail=3a8a3a",
      "Budgie Blue | parrot | body=6ab0f0 wing=2a6ad0 tuft=f0f0f0 tail=2a5ab0",
      "Burrow Benji | bunny | body=8a6a4a",
      "Cotton | bunny | body=f8f8f8 inner=ffb6c8 fx=hearts",
    ] },

  { id: "rockpool", name: "Rock Pool", emoji: "🦀",
    blurb: "Low tide, high spirits.",
    chars: [
      "Pinchy | crab |",
      "Sandy Scuttle | crab | body=e8b86a belly=f4dcb0",
      "Captain Claw | crab | body=c8303a hat=pirate r=2",
      "Inkwell | octopus |",
      "Coral Curl | octopus | body=ff7a6a mark=spots:ffc0b0",
      "Deep Blue Dora | octopus | body=3a5ad9 face=goggles fx=bubbles r=1",
      "Stripey Sid | fish | body=ffffff fin=f67a2a belly=ffffff mark=bands:f67a2a",
      "Puffer Percy | fish | body=f4d06a fin=e8a03a mark=speckle:a87a2a",
      "Tang | fish | body=3a7ad9 fin=f6d43a belly=6ab0e8",
      "Seaweed Sally | turtle | body=6ab07a shell=3a8a6a plate=6ac0a0 hat=flower:ff7ab0",
      "Tidepool Tess | snail | body=e8d0b0 shell=e87a8a spiral=a84a5a",
      "Jelly Jo | blob | body=d9a0f0 fx=bubbles",
      "Barnacle Bill | person | form=bald hat=sailor:2f5aa8 body=ffffff mark=bands:2f5aa8 skin=d8a07a pants=2f5aa8 face=stache:8a8a8a hair=aaaaaa",
      "Gull Gilbert | dove | body=f4f4f4 legs=f0a030 beak=f0c030 voice=honk",
    ] },

  { id: "garden", name: "Garden Crawlers", emoji: "🐞",
    blurb: "Small, busy and mostly very polite.",
    chars: [
      "Buzzby | bee |",
      "Queen Honeydew | bee | hat=crown r=3",
      "Bumble Boris | bee | body=f4b02a band=5a3a2a",
      "Dotty | ladybug |",
      "Lucky Seven | ladybug | body=f67a2a",
      "Goldbug | ladybug | body=f6c531 r=1",
      "Slowcoach Sid | snail |",
      "Twirl | snail | shell=a87ae8 spiral=6a4ab0",
      "Petal Snail | snail | shell=ff9ec4 spiral=d85a8a hat=flower:ffffff",
      "Grasshop Gus | frog | body=9ad04a belly=d8f0a0 face=glasses",
      "Beetleboo | ladybug | body=3a8a5a spot=2a4a3a",
      "Gnome Gardener | person | hat=party:d33a3a face=stache:ffffff form=bald body=3a7ad9 pants=6a4a3a skin=f0c0a0 hair=ffffff",
      "Sunny Sprout | blob | body=9ad04a hat=sprout",
      "Firefly Flo | bee | body=5a6a3a band=2a2a30 wing=f0fff0 fx=sparkle theme=fireflies r=2",
    ] },

  { id: "scales", name: "Scale Tales", emoji: "🦎",
    blurb: "Sun-lovers, rock-sitters and one tiny dragon.",
    chars: [
      "Zippy Gecko | lizard |",
      "Chamelia | lizard | body=5ad9a0 belly=f0f0a0 mark=rainbow r=2",
      "Spike | lizard | body=8a9a4a crest=5a6a2a",
      "Frilly Fran | lizard | body=e8a04a crest=d8603a",
      "Sunbask | lizard | body=d8b06a belly=f4e0b0 face=shades",
      "Sir Shellington | turtle | hat=tophat:2a2a30 face=monocle r=2",
      "Pebble | turtle | shell=8a8a90 plate=aaaab0 body=b0c0a0",
      "Rex Junior | dragon | body=6ab04a wing=4a8a3a",
      "Scaly Sue | dragon | body=d9a03a belly=f4e0a0 wing=c07a2a",
      "Newt Newton | lizard | body=f07a3a belly=f6d06a mark=spots:2a2a30 face=glasses",
      "Swampy | lizard | body=4a7a3a belly=a8c878 crest=3a5a2a",
      "Tortoise Tilda | turtle | shell=a87a4a plate=c89a6a body=b8a080 hat=bow:e84a8a",
      "Iggy Iguana | lizard | body=5ac05a crest=3a8a3a hat=cap:d33a3a",
      "Salamander Sal | lizard | body=2a2a30 belly=f6d43a mark=spots:f6d43a",
    ] },

  { id: "dragons", name: "Dragon Roost", emoji: "🐉",
    blurb: "Wings, horns, and the occasional sparkle.",
    chars: [
      "Ember | dragon | body=d9412e belly=f6d06a wing=a02a2a fx=embers theme=embers r=3",
      "Frostwing | dragon | body=8ad0f0 belly=e8f8ff wing=4a9ad9 fx=snow r=2",
      "Mossy | dragon |",
      "Shimmerscale | dragon | body=c08ae8 belly=f8d8ff wing=8a5ad0 fx=glitter r=2",
      "Puffball Posy | dragon | body=f4a0c0 belly=fff0f4 wing=e07aa0 hat=bow:ffffff",
      "Captain Scales | dragon | body=3a6ad9 hat=pirate r=1",
      "Moonbeam | pony | body=f4f4ff mane=c8b0ff horn=f6d743 fx=sparkle r=3",
      "Stardust Steed | pony | body=e8d0f8 mane=8a5ad9 horn=ffffff mark=stars:ffd23f r=2",
      "Prism | pony | body=ffffff mane=e84a8a horn=f6d743 mark=rainbow fx=rainbow r=3",
      "Wisp | ghost | body=d0f0ff fx=sparkle",
      "Gemma Gemback | turtle | shell=8a5ad9 plate=d0a0ff body=a0d0a0 fx=glitter",
      "Wizard Wobble | blob | body=8a5ad9 hat=wizard:3a3ab0",
      "Knightly Knox | person | hat=helmet:9aa3ad body=9aa3ad pants=6a6a78 back=cape:d33a3a",
      "Pixie Pip | person | back=wings:c0f0ff body=8ad08a form=bun hair=f6d06a skin=f4d0b0 fx=sparkle",
    ] },

  { id: "frights", name: "Friendly Frights", emoji: "🎃",
    blurb: "Spooky on the outside, cuddly all the way through.",
    chars: [
      "Boobert | ghost |",
      "Peekaboo | ghost | hat=bow:e84a8a",
      "Sheet Sherbet | ghost | body=ffe8f4 cheek=ff9ac0",
      "Gloom Glow | ghost | body=b8f0c0 fx=sparkle theme=fireflies r=2",
      "Bandage Benny | person | body=f0e8d0 pants=f0e8d0 skin=f0e8d0 form=bald mark=bands:c8bca0",
      "Count Cuddles | person | back=cape:3a1a3a body=2a2a30 pants=2a2a30 skin=e8e0f0 hair=2a2a30 neck=bowtie:d33a3a r=1",
      "Pumpkin Pete | fruit | body=f08a24 leaf=4a7a2a form=orange",
      "Batty | ghost | body=4a3a5a cheek=ff9ac0 hat=ears:4a3a5a",
      "Hazel Hex | person | hat=wizard:2a2a30 body=6a3a8a form=long hair=e8703a skin=f4d0b0",
      "Nightpaw | cat | body=2a2a30 inner=b870d0 fx=stars",
      "Goo Gus | blob | body=9ad04a mark=spots:6aa03a",
      "Bolt Buddy | robot | body=8ac07a accent=4a4a58 visor=2a3a2a fx=bolts",
      "Midnight Hoot | owl | body=4a3a5a disc=8a7aa0 tufts=2a2a3a",
      "Trick-or-Treat Tart | cupcake | body=f08a24 wrapper=2a2a30 cherry=a84ad9",
    ] },

  { id: "robots", name: "Robot Workshop", emoji: "🤖",
    blurb: "Nuts, bolts, and a lot of beeping.",
    chars: [
      "Beep | robot |",
      "Boop | robot | body=f0c040 accent=d9412e",
      "Widget | robot | body=d9412e accent=f6d43a visor=2a2a30",
      "Cogwheel Cody | robot | body=8a6a4a accent=d8a040 face=goggles",
      "Chromey | robot | body=e8eef4 accent=4ad9d9 r=1",
      "Rusty | robot | body=b86a3a accent=6a4a3a mark=speckle:7a3a1a",
      "Tinker Tot | robot | body=6ab0e8 hat=propeller",
      "Bolt Bird | chicken | body=b8c4cc comb=4a8fe8 wattle=4a8fe8 beak=6a6a70 legs=6a6a70 fx=bolts voice=clank r=2",
      "Clockwork Crab | crab | body=c8a040 belly=e8d08a fx=bolts",
      "Servo Pup | dog | body=b8c4cc ear=4a8fe8 muzzle=e8eef4 neck=collar:4a8fe8 voice=blip",
      "Mecha Mouse | mouse | body=9aa3ad inner=4ad9d9 tail=6a6a78 voice=blip",
      "Circuit Sam | person | body=4ad9a0 pants=2a3a4a face=goggles hair=3a3a3a form=curly skin=c89070",
      "Pixel | blob | body=4a8fe8 mark=check:2a5ab0 voice=blip r=1",
      "Kettle Bot | teapot | body=b8c4cc accent=4a8fe8 fx=bolts",
      "Radar Ray | robot | body=3a4a6a accent=f6d43a visor=4ad9d9 hat=headphones:f6d43a",
    ] },

  { id: "treats", name: "Tea & Treats", emoji: "🧁",
    blurb: "Pinkies out. Sprinkles on.",
    chars: [
      "Cupcake Cora | cupcake |",
      "Choc Chip | cupcake | body=8a5a3a wrapper=f4d06a cherry=f4f0e8",
      "Minty | cupcake | body=a0f0d0 wrapper=f08aa0",
      "Birthday Bun | cupcake | body=ffffff wrapper=8a5ad9 hat=party:e84a8a fx=confetti r=1",
      "Lemon Drizzle | cupcake | body=fff08a wrapper=f6c531 cherry=f6d43a",
      "Teapot Tom | teapot |",
      "Rosehip | teapot | body=f8b8c8 accent=ffffff mark=hearts:e85a8a",
      "Earl Grey | teapot | body=8a8a98 accent=d8c8a0 face=monocle r=1",
      "Chamomile | teapot | body=f6e08a accent=ffffff hat=flower:ffffff",
      "Custard Cat | cat | body=f6e08a inner=f4c0a0 neck=bow:e84a8a",
      "Sugar Mouse | mouse | body=ffc0d8 inner=ff8ab0 tail=ff8ab0",
      "Baker Betty | person | hat=chef body=ffffff pants=e84a8a form=bun hair=8a5a3a",
      "Macaron Maxi | blob | body=b8e0f8 mark=bands:f8c0d8",
      "Jam Tart Jess | fruit | body=d9303a leaf=4caf50 form=berry",
      "Biscuit Bear | bear | body=d9a060 muzzle=f4dcb0 neck=bowtie:4a8fe8",
    ] },

  { id: "fruit", name: "Fruit Stand", emoji: "🍎",
    blurb: "Fresh today, and in a great mood.",
    chars: [
      "Apple Annie | fruit |",
      "Granny Green | fruit | body=8ad04a face=glasses",
      "Tangerine Tom | fruit | body=f6922a form=orange",
      "Zesty Lou | fruit | body=f6e03a leaf=6ab04a form=lemon",
      "Pip Pear | fruit | body=c8d85a form=pear",
      "Berry Belle | fruit | body=e8304a leaf=3a9a3a form=berry",
      "Blueberry Bunch | fruit | body=4a5ad9 leaf=3a8a3a form=grape",
      "Grapeful Greg | fruit | body=8a4ab0 form=grape",
      "Lime Light | fruit | body=6ad04a form=lemon face=shades",
      "Peachy Keen | fruit | body=ffb88a face=blush",
      "Plum Pudding | fruit | body=7a3a6a",
      "Cherry Pop | fruit | body=d9203a leaf=3a8a3a hat=bow:ffffff",
      "Kiwi Kit | fruit | body=8a6a3a mark=speckle:5a4a2a form=lemon",
      "Melon Mel | fruit | body=6ab04a mark=stripes:3a7a2a",
      "Coco Nut | fruit | body=6a4a2a leaf=4caf50 mark=speckle:4a3a1a",
    ] },
];

Roster.build(COLLECTIONS, PLANS);
