// The roster: every character in Chicken Cross, one line each, grouped into
// collections. The line format is described above parseLine() in
// js/roster.js; in short:
//
//   "Name | plan | colour=hex ... hat=kind[:hex] neck= face= back= mark= fx= voice= theme= r=rarity unlock"
//
// All names and designs are original to Chicken Cross.
"use strict";

const COLLECTIONS = [
  { id: "founding", name: "Founding Flock", emoji: "🐔", unlock: "founding",
    blurb: "The twelve birds who crossed the very first road.",
    chars: [
      "Chicken | chicken | f=🐔 id=hen",
      "Rooster | rooster | f=🐓 id=rooster",
      "Chick | chick | f=🐤 id=chick",
      "Hatchling | chick | f=🐥 id=hatchling",
      "Duck | duck | f=🦆 id=duck",
      "Penguin | penguin | f=🐧 id=penguin",
      "Owl | owl | f=🦉 id=owl",
      "Flamingo | flamingo | f=🦩 id=flamingo",
      "Parrot | parrot | f=🦜 id=parrot",
      "Peacock | peacock | f=🦚 id=peacock",
      "Swan | swan | f=🦢 id=swan",
      "Dove | dove | f=🕊️ id=dove",
    ] },

  /* ============================================ the Prize Machine (290) */

  { id: "farmyard", name: "Farmyard Friends", emoji: "🚜",
    blurb: "Mud, hay and an early start.",
    chars: [
      "Tilly Truffle | pig | mark=spots:c9707f",
      "Sir Oinksalot | pig | body=f2b3a0 hat=tophat:3a3a44 neck=bowtie:d33a3a r=2",
      "Mudpuddle Maisie | pig | body=d99a7e snout=c8826a mark=patch:8a5a3c fx=drops",
      "Daisy Buttercup | cow | hat=flower:ffd23f",
      "Clover Moo | cow | patch=8a5a3c muzzle=f7c8b8 neck=bell",
      "Bramble Bull | cow | body=6a4a3a patch=3a2a24 horn=fff4d6 muzzle=c89a8a r=1",
      "Woolly Winifred | sheep | neck=scarf:e05a8a",
      "Dusty Fleece | sheep | body=e8dcc8 skin=6a4a3a",
      "Midnight Merino | sheep | body=4a4a58 skin=1d1d24 r=1",
      "Parsnip | bunny | body=e8e0d8 hat=straw:e05a8a",
      "Hay Bale Hattie | pony | body=d8a86a mane=f4e0b0 hat=straw:d33a3a",
      "Gravel Gertie | chicken | body=c98a4a mark=speckle:7a4a2a",
      "Farmer Fenwick | person | body=6a9a3a pants=3a5a8a hat=straw:6a9a3a hair=8a5a3a",
      "Tractor Tess | person | body=d9412e pants=3a4a6a hat=cap:d9412e form=braid hair=c8783a skin=e8b890",
      "Old Mac Rooster | rooster | body=c86a3a tail=2a4a2a hat=straw:3a7ad9 r=2",
    ] },

  { id: "woodland", name: "Woodland Wanderers", emoji: "🌲",
    blurb: "Rustlers of leaves and keepers of acorns.",
    chars: [
      "Fern Foxglove | fox |",
      "Russet Rascal | fox | body=c8582a neck=bandana:3a7ad9",
      "Silver Brush | fox | body=b8c0c8 socks=5a5a66 r=2",
      "Bramble Bear | bear |",
      "Honeypot Hugo | bear | body=d99a4a muzzle=f4dcb0 neck=scarf:d33a3a",
      "Moss Grizzle | bear | body=6a5a4a muzzle=b8a080 hat=sprout",
      "Prickles | hedgehog |",
      "Conker Quill | hedgehog | body=5a3a2a skin=f0dcc0 hat=cap:3a8a3a",
      "Acorn Ada | mouse | body=a8805a inner=ffc0c8 hat=beret:6a9a3a",
      "Hazel Hoard | mouse | body=c8a078 back=backpack:d98e32",
      "Tawny Hoot | owl | body=b07a4a disc=f0dcc0 hat=laurel",
      "Barnaby Barn Owl | owl | body=e8c890 disc=ffffff tufts=d8b070 r=1",
      "Pip Woodpecker | parrot | body=2a2a30 wing=f4f4f4 tuft=d33a3a tail=2a2a30 beak=6a6a70 legs=6a6a70",
      "Fawn Hollow | pony | body=c8905a mane=8a5a3a mark=spots:f4e8d8",
      "Toadstool Tim | frog | body=8a6a4a belly=d8c8a0 hat=beret:d33a3a",
    ] },

  { id: "pond", name: "Pond & River", emoji: "🐸",
    blurb: "Paddlers, dabblers and one very slow swimmer.",
    chars: [
      "Lily Leapwell | frog | hat=flower:ff9ec4",
      "Bogsworth | frog | body=4a7a3a belly=a8c878 face=monocle",
      "Tadpole Tom | frog | body=3a5a3a belly=8aa878 fx=bubbles",
      "Marsh Mallow | duck | body=c8b8a0 head=f4f0e8 ring=e8c8a0",
      "Dabbler Dot | duck | head=3a5ad9 body=6a6a70",
      "Paddles | duck | body=f6d43a head=f6d43a ring=f6d43a beak=f28c28 fx=bubbles voice=squeak",
      "Grace Glide | swan | hat=tiara:e84a8a",
      "Nocturne | swan | body=2a2a30 beak=d33a3a mask=1d1d24 r=2",
      "Shelly Slowtide | turtle |",
      "Mossback | turtle | shell=5a6a3a plate=8a9a5a hat=sprout",
      "Reed Runner | lizard | body=6aa04a belly=d0e8a0",
      "Kingfisher Kit | parrot | body=2a8ad9 wing=1a6ab0 tuft=2a8ad9 tail=1a5a9a beak=2a2a30 mark=belly:f08a3a",
      "Crayfish Cal | crab | body=a8503a belly=d88a6a",
      "Harriet Heron | flamingo | body=b8c0c8 head=e8ecf0 wing=8a929a legs=d8c070 beak=e8c040 beakTip=d8a030",
    ] },

  { id: "pets", name: "Pet Parade", emoji: "🐾",
    blurb: "Everyone's best friend, and a goldfish.",
    chars: [
      "Whiskers McPurr | cat |",
      "Marmalade | cat | mark=stripes:c8702a",
      "Inky | cat | body=2a2a30 inner=d88aa0 neck=collar:d33a3a",
      "Snowdrop | cat | body=f4f4f4 inner=ffb6c8 neck=bell",
      "Biscuit | dog |",
      "Pepper Pup | dog | body=f4f0e8 ear=2a2a30 muzzle=ffffff mark=spots:2a2a30",
      "Sir Waggington | dog | body=6a4a3a ear=3a2a1a muzzle=c8a078 hat=tophat:2a2a30 neck=bowtie:3a3a44 r=2",
      "Nibbles | mouse |",
      "Hamish Hamster | mouse | body=e8a860 inner=f4c8a0 tail=f4c8a0",
      "Goldie | fish | body=f6a52a fin=f67a2a",
      "Bubbles McFin | fish | body=6ab0e8 fin=3a7ad9 belly=e8f4ff fx=bubbles",
      "Polly Perch | parrot | body=5ac04a wing=f6d43a tuft=f6d43a tail=3a8a3a",
      "Budgie Blue | parrot | body=6ab0f0 wing=2a6ad0 tuft=f0f0f0 tail=2a5ab0",
      "Burrow Benji | bunny | body=8a6a4a",
      "Cotton | bunny | body=f8f8f8 inner=ffb6c8 fx=hearts",
    ] },

  { id: "rockpool", name: "Rock Pool", emoji: "🦀",
    blurb: "Low tide, high spirits.",
    chars: [
      "Pinchy | crab |",
      "Sandy Scuttle | crab | body=e8b86a belly=f4dcb0",
      "Captain Claw | crab | body=c8303a hat=pirate r=2",
      "Inkwell | octopus |",
      "Coral Curl | octopus | body=ff7a6a mark=spots:ffc0b0",
      "Deep Blue Dora | octopus | body=3a5ad9 face=goggles fx=bubbles r=1",
      "Stripey Sid | fish | body=ffffff fin=f67a2a belly=ffffff mark=bands:f67a2a",
      "Puffer Percy | fish | body=f4d06a fin=e8a03a mark=speckle:a87a2a",
      "Tang | fish | body=3a7ad9 fin=f6d43a belly=6ab0e8",
      "Seaweed Sally | turtle | body=6ab07a shell=3a8a6a plate=6ac0a0 hat=flower:ff7ab0",
      "Tidepool Tess | snail | body=e8d0b0 shell=e87a8a spiral=a84a5a",
      "Jelly Jo | blob | body=d9a0f0 fx=bubbles",
      "Barnacle Bill | person | form=bald hat=sailor:2f5aa8 body=ffffff mark=bands:2f5aa8 skin=d8a07a pants=2f5aa8 face=stache:8a8a8a hair=aaaaaa",
      "Gull Gilbert | dove | body=f4f4f4 legs=f0a030 beak=f0c030 voice=honk",
    ] },

  { id: "garden", name: "Garden Crawlers", emoji: "🐞",
    blurb: "Small, busy and mostly very polite.",
    chars: [
      "Buzzby | bee |",
      "Queen Honeydew | bee | hat=crown r=3",
      "Bumble Boris | bee | body=f4b02a band=5a3a2a",
      "Dotty | ladybug |",
      "Lucky Seven | ladybug | body=f67a2a",
      "Goldbug | ladybug | body=f6c531 r=1",
      "Slowcoach Sid | snail |",
      "Twirl | snail | shell=a87ae8 spiral=6a4ab0",
      "Petal Snail | snail | shell=ff9ec4 spiral=d85a8a hat=flower:ffffff",
      "Grasshop Gus | frog | body=9ad04a belly=d8f0a0 face=glasses",
      "Beetleboo | ladybug | body=3a8a5a spot=2a4a3a",
      "Gnome Gardener | person | hat=party:d33a3a face=stache:ffffff form=bald body=3a7ad9 pants=6a4a3a skin=f0c0a0 hair=ffffff",
      "Sunny Sprout | blob | body=9ad04a hat=sprout",
      "Firefly Flo | bee | body=5a6a3a band=2a2a30 wing=f0fff0 fx=sparkle theme=fireflies r=2",
    ] },

  { id: "scales", name: "Scale Tales", emoji: "🦎",
    blurb: "Sun-lovers, rock-sitters and one tiny dragon.",
    chars: [
      "Zippy Gecko | lizard |",
      "Chamelia | lizard | body=5ad9a0 belly=f0f0a0 mark=rainbow r=2",
      "Spike | lizard | body=8a9a4a crest=5a6a2a",
      "Frilly Fran | lizard | body=e8a04a crest=d8603a",
      "Sunbask | lizard | body=d8b06a belly=f4e0b0 face=shades",
      "Sir Shellington | turtle | hat=tophat:2a2a30 face=monocle r=2",
      "Pebble | turtle | shell=8a8a90 plate=aaaab0 body=b0c0a0",
      "Rex Junior | dragon | body=6ab04a wing=4a8a3a",
      "Scaly Sue | dragon | body=d9a03a belly=f4e0a0 wing=c07a2a",
      "Newt Newton | lizard | body=f07a3a belly=f6d06a mark=spots:2a2a30 face=glasses",
      "Swampy | lizard | body=4a7a3a belly=a8c878 crest=3a5a2a",
      "Tortoise Tilda | turtle | shell=a87a4a plate=c89a6a body=b8a080 hat=bow:e84a8a",
      "Iggy Iguana | lizard | body=5ac05a crest=3a8a3a hat=cap:d33a3a",
      "Salamander Sal | lizard | body=2a2a30 belly=f6d43a mark=spots:f6d43a",
    ] },

  { id: "dragons", name: "Dragon Roost", emoji: "🐉",
    blurb: "Wings, horns, and the occasional sparkle.",
    chars: [
      "Ember | dragon | body=d9412e belly=f6d06a wing=a02a2a fx=embers theme=embers r=3",
      "Frostwing | dragon | body=8ad0f0 belly=e8f8ff wing=4a9ad9 fx=snow r=2",
      "Mossy | dragon |",
      "Shimmerscale | dragon | body=c08ae8 belly=f8d8ff wing=8a5ad0 fx=glitter r=2",
      "Puffball Posy | dragon | body=f4a0c0 belly=fff0f4 wing=e07aa0 hat=bow:ffffff",
      "Captain Scales | dragon | body=3a6ad9 hat=pirate r=1",
      "Moonbeam | pony | body=f4f4ff mane=c8b0ff horn=f6d743 fx=sparkle r=3",
      "Stardust Steed | pony | body=e8d0f8 mane=8a5ad9 horn=ffffff mark=stars:ffd23f r=2",
      "Prism | pony | body=ffffff mane=e84a8a horn=f6d743 mark=rainbow fx=rainbow r=3",
      "Wisp | ghost | body=d0f0ff fx=sparkle",
      "Gemma Gemback | turtle | shell=8a5ad9 plate=d0a0ff body=a0d0a0 fx=glitter",
      "Wizard Wobble | blob | body=8a5ad9 hat=wizard:3a3ab0",
      "Knightly Knox | person | hat=helmet:9aa3ad body=9aa3ad pants=6a6a78 back=cape:d33a3a",
      "Pixie Pip | person | back=wings:c0f0ff body=8ad08a form=bun hair=f6d06a skin=f4d0b0 fx=sparkle",
    ] },

  { id: "frights", name: "Friendly Frights", emoji: "🎃",
    blurb: "Spooky on the outside, cuddly all the way through.",
    chars: [
      "Boobert | ghost |",
      "Peekaboo | ghost | hat=bow:e84a8a",
      "Sheet Sherbet | ghost | body=ffe8f4 cheek=ff9ac0",
      "Gloom Glow | ghost | body=b8f0c0 fx=sparkle theme=fireflies r=2",
      "Bandage Benny | person | body=f0e8d0 pants=f0e8d0 skin=f0e8d0 form=bald mark=bands:c8bca0",
      "Count Cuddles | person | back=cape:3a1a3a body=2a2a30 pants=2a2a30 skin=e8e0f0 hair=2a2a30 neck=bowtie:d33a3a r=1",
      "Pumpkin Pete | fruit | body=f08a24 leaf=4a7a2a form=orange",
      "Batty | ghost | body=4a3a5a cheek=ff9ac0 hat=ears:4a3a5a",
      "Hazel Hex | person | hat=wizard:2a2a30 body=6a3a8a form=long hair=e8703a skin=f4d0b0",
      "Nightpaw | cat | body=2a2a30 inner=b870d0 fx=stars",
      "Goo Gus | blob | body=9ad04a mark=spots:6aa03a",
      "Bolt Buddy | robot | body=8ac07a accent=4a4a58 visor=2a3a2a fx=bolts",
      "Midnight Hoot | owl | body=4a3a5a disc=8a7aa0 tufts=2a2a3a",
      "Trick-or-Treat Tart | cupcake | body=f08a24 wrapper=2a2a30 cherry=a84ad9",
    ] },

  { id: "robots", name: "Robot Workshop", emoji: "🤖",
    blurb: "Nuts, bolts, and a lot of beeping.",
    chars: [
      "Beep | robot |",
      "Boop | robot | body=f0c040 accent=d9412e",
      "Widget | robot | body=d9412e accent=f6d43a visor=2a2a30",
      "Cogwheel Cody | robot | body=8a6a4a accent=d8a040 face=goggles",
      "Chromey | robot | body=e8eef4 accent=4ad9d9 r=1",
      "Rusty | robot | body=b86a3a accent=6a4a3a mark=speckle:7a3a1a",
      "Tinker Tot | robot | body=6ab0e8 hat=propeller",
      "Bolt Bird | chicken | body=b8c4cc comb=4a8fe8 wattle=4a8fe8 beak=6a6a70 legs=6a6a70 fx=bolts voice=clank r=2",
      "Clockwork Crab | crab | body=c8a040 belly=e8d08a fx=bolts",
      "Servo Pup | dog | body=b8c4cc ear=4a8fe8 muzzle=e8eef4 neck=collar:4a8fe8 voice=blip",
      "Mecha Mouse | mouse | body=9aa3ad inner=4ad9d9 tail=6a6a78 voice=blip",
      "Circuit Sam | person | body=4ad9a0 pants=2a3a4a face=goggles hair=3a3a3a form=curly skin=c89070",
      "Pixel | blob | body=4a8fe8 mark=check:2a5ab0 voice=blip r=1",
      "Kettle Bot | teapot | body=b8c4cc accent=4a8fe8 fx=bolts",
      "Radar Ray | robot | body=3a4a6a accent=f6d43a visor=4ad9d9 hat=headphones:f6d43a",
    ] },

  { id: "treats", name: "Tea & Treats", emoji: "🧁",
    blurb: "Pinkies out. Sprinkles on.",
    chars: [
      "Cupcake Cora | cupcake |",
      "Choc Chip | cupcake | body=8a5a3a wrapper=f4d06a cherry=f4f0e8",
      "Minty | cupcake | body=a0f0d0 wrapper=f08aa0",
      "Birthday Bun | cupcake | body=ffffff wrapper=8a5ad9 hat=party:e84a8a fx=confetti r=1",
      "Lemon Drizzle | cupcake | body=fff08a wrapper=f6c531 cherry=f6d43a",
      "Teapot Tom | teapot |",
      "Rosehip | teapot | body=f8b8c8 accent=ffffff mark=hearts:e85a8a",
      "Earl Grey | teapot | body=8a8a98 accent=d8c8a0 face=monocle r=1",
      "Chamomile | teapot | body=f6e08a accent=ffffff hat=flower:ffffff",
      "Custard Cat | cat | body=f6e08a inner=f4c0a0 neck=bow:e84a8a",
      "Sugar Mouse | mouse | body=ffc0d8 inner=ff8ab0 tail=ff8ab0",
      "Baker Betty | person | hat=chef body=ffffff pants=e84a8a form=bun hair=8a5a3a",
      "Macaron Maxi | blob | body=b8e0f8 mark=bands:f8c0d8",
      "Jam Tart Jess | fruit | body=d9303a leaf=4caf50 form=berry",
      "Biscuit Bear | bear | body=d9a060 muzzle=f4dcb0 neck=bowtie:4a8fe8",
    ] },

  { id: "fruit", name: "Fruit Stand", emoji: "🍎",
    blurb: "Fresh today, and in a great mood.",
    chars: [
      "Apple Annie | fruit |",
      "Granny Green | fruit | body=8ad04a face=glasses",
      "Tangerine Tom | fruit | body=f6922a form=orange",
      "Zesty Lou | fruit | body=f6e03a leaf=6ab04a form=lemon",
      "Pip Pear | fruit | body=c8d85a form=pear",
      "Berry Belle | fruit | body=e8304a leaf=3a9a3a form=berry",
      "Blueberry Bunch | fruit | body=4a5ad9 leaf=3a8a3a form=grape",
      "Grapeful Greg | fruit | body=8a4ab0 form=grape",
      "Lime Light | fruit | body=6ad04a form=lemon face=shades",
      "Peachy Keen | fruit | body=ffb88a face=blush",
      "Plum Pudding | fruit | body=7a3a6a",
      "Cherry Pop | fruit | body=d9203a leaf=3a8a3a hat=bow:ffffff",
      "Kiwi Kit | fruit | body=8a6a3a mark=speckle:5a4a2a form=lemon",
      "Melon Mel | fruit | body=6ab04a mark=stripes:3a7a2a",
      "Coco Nut | fruit | body=6a4a2a leaf=4caf50 mark=speckle:4a3a1a",
    ] },

  { id: "town", name: "Town Folk", emoji: "🏘️",
    blurb: "The neighbours. Everyone waves.",
    chars: [
      "Letterbox Lena | person | hat=cap:d33a3a body=d9412e back=backpack:8a5a3a form=long hair=3a2a1a skin=c89070",
      "Crossing Carol | person | hat=cap:f6c531 body=f6c531 mark=bands:ffffff pants=2a3a5a form=bun hair=aaaaaa",
      "Firefighter Finn | person | hat=helmet:d9412e body=d9412e pants=f6c531 hair=d87a3a",
      "Doctor Dee | person | body=ffffff pants=3a7ad9 face=glasses form=curly hair=2a2a2a skin=8a5a3a",
      "Chef Charlie | person | hat=chef body=ffffff pants=2a2a30 face=stache:5a3a22 skin=f0c0a0",
      "Builder Brick | person | hat=helmet:f6c531 body=f08a24 pants=3a5a8a skin=d8a07a hair=3a2a1a",
      "Painter Poppy | person | hat=beret:e84a8a body=f4f0e8 mark=spots:4a8fe8 form=long hair=e8703a",
      "Librarian Lou | person | body=6a9a6a face=glasses form=bun hair=8a8a8a skin=e8c0a0",
      "Grandpa Gus | person | form=bald hair=e8e8e8 face=stache:e8e8e8 body=8a6a4a neck=bowtie:3a7ad9 skin=f0c8a8",
      "Nana Nell | person | form=curly hair=e8e8f4 body=b88ad9 neck=scarf:e85a8a",
      "Mayor Marigold | person | hat=tophat:2a2a30 body=3a3a58 neck=medal hair=6a4a2a skin=c89070 r=2",
      "Busker Billie | person | hat=bucket:6a9a3a body=f6c531 back=backpack:6a4a2a form=long hair=2a2a2a skin=a86a4a fx=notes",
      "Paper Pip | person | hat=cap:3a7ad9 body=ffffff pants=6a6a78 back=backpack:3a7ad9 hair=d8a050",
      "Gardener Gwen | person | hat=straw:6ab04a body=6ab04a pants=8a6a4a form=braid hair=c8783a",
      "Barista Bea | person | body=6a4a3a hat=beanie:e8d8c0 hair=2a2a30 skin=8a5a3a",
    ] },

  { id: "adventurers", name: "Adventurers", emoji: "🧭",
    blurb: "Packed, mapped and ready to go.",
    chars: [
      "Explorer Ellie | person | hat=bucket:d8b070 body=d8b070 back=backpack:6a4a2a form=braid hair=6a3a1a",
      "Captain Cora | person | hat=pirate body=ffffff pants=2a2a30 back=cape:d33a3a form=long hair=2a2a30 skin=c89070 r=1",
      "Sky Pilot Sam | person | face=goggles body=8a5a3a neck=scarf:ffffff hair=d8a050",
      "Mountain Moss | bear | hat=beanie:d33a3a back=backpack:3a7ad9",
      "Scout Fennel | fox | hat=bucket:6a8a3a back=backpack:8a5a3a",
      "Diver Dani | person | hat=snorkel:f6c531 body=2a2a30 pants=2a2a30 face=goggles skin=d8a07a fx=bubbles",
      "Jungle Jack | person | hat=straw:3a7a3a body=8a9a5a pants=6a5a3a skin=a86a4a hair=2a2a2a",
      "Dune Rider | pony | body=e8c890 mane=8a5a3a neck=bandana:d33a3a",
      "Viking Valda | person | hat=viking:8a5a3a body=8a5a3a pants=6a6a78 form=braid hair=f6d06a r=1",
      "Sir Nibbles | mouse | hat=helmet:9aa3ad back=cape:3a7ad9 r=1",
      "Ranger Rae | dog | hat=cowboy:8a5a3a neck=bandana:d33a3a",
      "Cowpoke Kip | person | hat=cowboy:8a5a3a body=d9412e mark=check:8a2a2a pants=3a5a8a",
      "Compass Crab | crab | hat=bucket:6a8a3a",
      "Rafting Rita | frog | hat=helmet:f6c531 back=backpack:d9412e",
      "Treasure Tortoise | turtle | hat=pirate shell=8a6a3a plate=f6d43a r=2",
    ] },

  { id: "frosty", name: "Frosty Peaks", emoji: "❄️",
    blurb: "Crisp air, fluffy coats, cold feet.",
    chars: [
      "Polar Pip | bear | body=f4f8ff muzzle=e8e8f0",
      "Snowball | owl | body=f4f8ff disc=ffffff tufts=e8ecf0 mark=speckle:3a3a44",
      "Arctic Arlo | fox | body=f4f8ff socks=c8d0d8",
      "Frost Hare | bunny | body=f4f8ff inner=c8e0f8 fx=snow",
      "Wobble Waddle | penguin | hat=beanie:3a7ad9 neck=scarf:d33a3a",
      "Emperor Ernest | penguin | body=2a3a4a belly=fff8e0 hat=crown r=2",
      "Icicle Iggy | penguin | body=5a8ad9 belly=e8f4ff fx=snow",
      "Yeti Yolanda | bear | body=e8f0ff muzzle=a8c0e0 r=2",
      "Snowman Sid | blob | body=ffffff hat=tophat:2a2a30 neck=scarf:d33a3a fx=snow",
      "Mitten Mouse | mouse | body=d0d8e8 hat=beanie:e84a8a",
      "Skier Skye | person | hat=beanie:3a7ad9 face=goggles body=e84a8a pants=2a3a5a",
      "Husky Hal | dog | body=8a9aaa ear=4a5a6a muzzle=ffffff",
      "Glacier Gus | turtle | shell=8ad0f0 plate=d0f0ff body=c8e0f0",
      "Snowtrot | pony | body=a87a5a mane=f4f8ff hat=antlers",
    ] },

  { id: "desert", name: "Desert Drifters", emoji: "🌵",
    blurb: "Sun hats on. Water bottles full.",
    chars: [
      "Fennec Fizz | fox | body=f0d0a0 chest=fff4e0 socks=d8a870 tip=f0d0a0",
      "Sandy Skip | bunny | body=d8b890 inner=f4c0a0",
      "Cactus Cal | blob | body=5aa04a hat=flower:ff7ab0",
      "Sidewinder Sol | lizard | body=d8b070 belly=f4e0b0 mark=speckle:8a6a3a",
      "Gila Gail | lizard | body=f08a4a belly=f4c080 mark=spots:2a2a30",
      "Desert Tortoise Dot | turtle | shell=b89a6a plate=d8c090 body=c8b080",
      "Humphrey | pony | body=d8b070 mane=a87a4a neck=bell",
      "Sprinter Quail | chick | body=a88a6a beak=3a3a44 legs=6a6a70 mark=speckle:5a4a3a",
      "Oasis Olly | frog | body=5ab0a0 belly=d0f0e0 hat=straw:3a7ad9",
      "Sunhat Sadie | person | hat=straw:e84a8a body=f6d43a form=long hair=8a3a1a skin=a86a4a face=shades",
      "Scarab Sam | ladybug | body=3a8ab0 spot=2a4a6a fx=glitter r=1",
      "Mirage | ghost | body=ffe8c0 fx=sparkle r=1",
      "Dingo Dan | dog | body=d8903a ear=b86a2a muzzle=f4e0c0",
      "Pricklepear Pru | fruit | body=e84a8a form=pear mark=speckle:ffffff",
    ] },

  { id: "jungle", name: "Jungle Canopy", emoji: "🌴",
    blurb: "Loud, bright and hanging about.",
    chars: [
      "Tango Toucan | parrot | body=2a2a30 wing=2a2a30 tuft=2a2a30 tail=2a2a30 beak=f6922a mark=belly:f6d43a",
      "Macaw Max | parrot | body=3a7ad9 wing=f6d43a tuft=3a7ad9 tail=3a5ab0",
      "Scarlet Sky | parrot | body=e8303a wing=f6d43a tail=3a7ad9 tuft=e8303a r=1",
      "Tree Frog Tia | frog | body=5ad05a belly=f6f0a0 fx=drops",
      "Jewel Frog | frog | body=3a8ad9 belly=2a2a30 mark=spots:2a2a30 r=1",
      "Chameleon Chloe | lizard | body=8ad04a crest=4a9a3a mark=rainbow fx=rainbow r=2",
      "Tiger Tilly | cat | body=f08a2a inner=ffc0a0 mark=stripes:2a2a30 r=1",
      "Leopard Leo | cat | body=f0c060 mark=spots:8a5a2a",
      "Panther Pax | cat | body=2a2a30 inner=5a4a6a r=1",
      "Peacock Paloma | peacock | body=4ad0a0 head=3a7ad9 tail=d9a03a crown=3a7ad9 r=1",
      "Vine Swinger Vic | person | hat=straw:4a8a3a body=4a8a3a skin=c89070 hair=2a2a2a form=curly",
      "Rhino Beetle Rhi | ladybug | body=4a3a2a spot=2a2a1a hat=horns:c8b890",
      "Flutterby Fay | bee | body=ff9ad0 band=8a5ad9 wing=c0f0ff fx=petals",
      "Mango Moe | fruit | body=f6a52a form=pear",
      "Silverback Sid | bear | body=3a3a40 muzzle=6a6a70 r=1",
    ] },

  { id: "night", name: "Night Shift", emoji: "🌙",
    blurb: "Wide awake while everyone else is asleep.",
    chars: [
      "Hoot Nanny | owl | body=5a4a6a disc=c8b8e0 tufts=3a2a4a face=glasses",
      "Luna Moth | bee | body=d0f0c0 band=a8d8a0 wing=d0ffd0 fx=sparkle",
      "Firebug Freddie | bee | body=3a3a2a band=2a2a20 wing=fff8a0 fx=sparkle theme=fireflies r=1",
      "Noctis | fox | body=4a4a6a chest=c8c8e0 socks=2a2a40 tip=c8c8e0",
      "Badger Bob | bear | body=4a4a50 muzzle=ffffff",
      "Hedgehog Hush | hedgehog | body=4a3a4a skin=d8c8c0",
      "Rascal Raccoon | dog | body=8a8a90 ear=4a4a50 muzzle=f0f0f0 face=mask:2a2a30",
      "Stargazer Stella | person | hat=wizard:2a3a6a body=2a3a6a mark=stars:ffd23f form=long hair=f6d06a fx=stars r=2",
      "Night Watch Walt | person | hat=cap:2a3a5a body=2a3a5a pants=2a2a30 hair=6a4a2a skin=c89070",
      "Sleepy Sheep | sheep | hat=beanie:6a8ad9 body=e8e8f8",
      "Moon Blob | blob | body=f4f0c0 mark=speckle:c8c0a0 fx=stars",
      "Glow Worm Gil | snail | shell=6ad08a spiral=3a8a5a body=c8f0a0 fx=sparkle",
      "Shadow Cat | cat | body=3a3a4a inner=8a6aa0",
      "Lantern Larry | robot | body=f6d06a accent=f6922a visor=4a3a2a hat=miner r=1",
    ] },

  { id: "rainbow", name: "Rainbow Parade", emoji: "🌈",
    blurb: "Old friends in brand-new colours.",
    chars: [
      "Ruby Hen | chicken | body=e84a4a comb=f6d43a wattle=f6d43a",
      "Sunset Hen | chicken | body=f6922a comb=d9303a wattle=d9303a",
      "Lemon Chick | chick | body=fff08a",
      "Mint Chick | chick | body=9af0c0 beak=f08aa0 legs=f08aa0",
      "Sky Duck | duck | body=8ac8f0 head=3a7ad9",
      "Violet Dove | dove | body=c8a8f0",
      "Coral Flamingo | flamingo | body=ff8a6a head=ffa88a wing=f0704a",
      "Indigo Owl | owl | body=4a4ab0 disc=b0b0f0 tufts=2a2a80",
      "Gilded Swan | swan | body=f6d06a beak=d9412e fx=glitter r=2",
      "Rainbow Rooster | rooster | body=ffffff mark=rainbow tail=8a5ad9 r=2",
      "Prism Parrot | parrot | body=f0e030 wing=e84a8a tail=3a7ad9 tuft=5ad05a fx=rainbow r=1",
      "Bubblegum Pig | pig | body=ff8ad0 snout=ff5ab0",
      "Lilac Lamb | sheep | body=e0c8f8 skin=8a6ab0",
      "Aqua Peacock | peacock | body=2ad0c0 head=2a8ad0 tail=5a4ad0 crown=2a8ad0",
      "Neon Blob | blob | body=f03ad9 fx=glitter theme=neon r=3",
    ] },

  { id: "space", name: "Space Cadets", emoji: "🚀",
    blurb: "Crossing roads is easy. Try crossing galaxies.",
    chars: [
      "Astro Annie | person | hat=astronaut body=f4f4f4 back=jetpack:9aa3ad pants=f4f4f4 hair=6a4a2a skin=c89070 r=1",
      "Rocket Rudy | person | hat=astronaut body=d9412e back=jetpack:f6c531 pants=d9412e hair=f6d06a fx=stars r=2",
      "Zorp | blob | body=8ad04a hat=sprout:5ad05a voice=blip",
      "Glorp | octopus | body=5ad0a0 fx=stars",
      "Blip | robot | body=f4f4f4 accent=e84a4a visor=2a2a30",
      "Moon Mouse | mouse | body=d8d8e8 hat=astronaut back=jetpack:e84a8a",
      "Comet Kitty | cat | body=f4f4ff inner=b0a0f0 back=jetpack:8a5ad9 fx=stars",
      "Space Pup | dog | hat=astronaut body=f4d06a ear=c89a3a muzzle=fff0d0",
      "Nova | ghost | body=c0d0ff fx=sparkle theme=stardust r=2",
      "Satellite Sid | robot | body=9aa3ad accent=f6c531 hat=miner:9aa3ad back=wings:4a8fe8",
      "Galaxy Guppy | fish | body=5a3ab0 fin=d05ad0 mark=stars:ffffff fx=stars r=1",
      "Martian Milo | person | body=5ad05a skin=9ae07a pants=3a3a58 hat=sprout:9ae07a form=bald hair=9ae07a",
      "Saucer Sue | blob | body=b8c4cc mark=bands:4ad9d9 hat=astronaut",
      "Meteor Mo | dragon | body=6a5a7a belly=f08a3a wing=4a3a5a fx=embers",
    ] },

  /* ================================== achievements and milestones (68) */

  { id: "champions", name: "World Champions", emoji: "🏆",
    blurb: "Finish a world to meet its champion.",
    chars: [
      "Meadow Marshal | chicken | hat=straw:6ab04a neck=medal a=world:0 r=2",
      "City Slicker | dove | body=9aa3ad beak=e8a040 neck=tie:3a7ad9 a=world:1 r=2",
      "River Ranger | duck | hat=bucket:3a8a5a a=world:2 r=2",
      "Frosty Flyer | penguin | hat=beanie:8ad0f0 neck=scarf:3a7ad9 a=world:3 r=2",
      "Rush Hour Rosie | chick | hat=helmet:f6922a face=shades a=world:4 r=2",
      "Night Rider Nyx | owl | body=3a3a58 disc=8a8ab0 tufts=2a2a40 face=shades a=world:5 r=3",
      "Desert Dasher | rooster | body=e8c890 tail=a8703a hat=cowboy:8a5a3a a=world:6 r=3",
      "Jungle Jumper | parrot | hat=straw:4a8a3a back=backpack:8a5a3a a=world:7 r=3",
      "Station Master | person | hat=cap:2a3a5a body=2a3a5a neck=tie:d33a3a face=stache:6a4a2a skin=f0c8a8 hair=6a4a2a a=world:8 r=3",
      "Volcano Victor | dragon | body=6a3a2a belly=f08a3a wing=d9412e hat=crown fx=embers theme=embers a=world:9 r=4",
    ] },

  { id: "stars", name: "Star Collectors", emoji: "⭐",
    blurb: "Every star in a world, and stars by the handful.",
    chars: [
      "Sunflower Star | chick | hat=flower:f6d43a mark=stars:f6d43a a=world3:0:12 r=2",
      "Skyline Star | cat | body=6a7a8a mark=stars:f6d43a hat=beret:3a3a58 a=world3:1:12 r=2",
      "Rapids Star | fish | body=3a9ad9 fin=f6d43a mark=stars:f6d43a a=world3:2:12 r=2",
      "Snowflake Star | bunny | body=e8f4ff hat=beanie:8ad0f0 fx=snow a=world3:3:12 r=2",
      "Traffic Star | robot | body=f6d43a accent=d9412e visor=2a2a30 a=world3:4:12 r=3",
      "Moonlight Star | ghost | body=d0d8ff hat=halo fx=stars a=world3:5:12 r=3",
      "Sandstorm Star | fox | body=e8b060 face=goggles a=world3:6:12 r=3",
      "Canopy Star | frog | body=4ac04a mark=stars:f6d43a hat=laurel a=world3:7:12 r=3",
      "Timetable Star | pony | body=8a5a3a mane=2a2a30 hat=cap:d33a3a a=world3:8:12 r=3",
      "Lava Star | blob | body=f0703a mark=stars:f6d43a fx=embers a=world3:9:12 r=4",
      "Bronze Beak | chicken | body=c8803a comb=a8603a wattle=a8603a neck=medal:c8803a a=stars:30 r=1",
      "Silver Beak | chicken | body=c8d0d8 comb=9aa3ad wattle=9aa3ad neck=medal:c8d0d8 a=stars:60 r=2",
      "Golden Beak | chicken | body=f6d06a comb=d9a02a wattle=d9a02a neck=medal:f6c531 fx=sparkle a=stars:90 r=3",
      "Starlight Hen | chicken | body=fff8d0 hat=crown mark=stars:f6c531 fx=stars theme=stardust a=stars:120 r=4",
    ] },

  { id: "longhaul", name: "Long Haul Club", emoji: "🏁",
    blurb: "For going further than you did last time.",
    chars: [
      "First Steps Fern | chick | hat=cap:3a7ad9 a=best:25 r=1",
      "Halfway Hal | duck | neck=scarf:f6922a a=best:50 r=1",
      "Steady Stan | turtle | hat=cap:d33a3a a=best:75 r=1",
      "Century Cluck | chicken | hat=party:f6c531 neck=medal a=best:100 r=2",
      "Marathon Mo | dog | hat=cap:ffffff neck=medal:c8d0d8 a=best:150 r=2",
      "Longstride Lola | flamingo | hat=cap:e84a8a a=best:200 r=3",
      "Farflung Finch | dove | body=f6d06a beak=f28c28 neck=scarf:d33a3a a=best:250 r=3",
      "Horizon Hawk | parrot | body=8a5a3a wing=6a4a2a tail=5a3a1a tuft=8a5a3a beak=f6c531 a=best:300 r=3",
      "Endless Ernie | robot | body=f6c531 back=jetpack:d9412e fx=stars a=best:400 r=4",
      "Lanekeeper Legend | rooster | body=f6d06a tail=d9412e hat=crown back=cape:8a5ad9 fx=glitter theme=stardust a=best:500 r=4",
    ] },

  { id: "regulars", name: "Regulars", emoji: "🎟️",
    blurb: "For coming back, and hopping lots.",
    chars: [
      "Newcomer Nia | chick | hat=bow:e84a8a a=runs:10 r=1",
      "Regular Reggie | pig | hat=cap:3a7ad9 a=runs:25 r=1",
      "Frequent Flapper | dove | back=backpack:d98e32 a=runs:50 r=2",
      "Centurion Hattie | sheep | hat=laurel neck=medal a=runs:100 r=2",
      "Loyal Lotte | dog | neck=collar:e84a8a hat=crown a=runs:250 r=3",
      "Evergreen Ed | owl | hat=laurel neck=medal a=runs:500 r=4",
      "Hopscotch Hugo | bunny | a=hops:1000 r=1",
      "Springy Sprocket | robot | body=5ad05a hat=propeller a=hops:5000 r=2",
      "Leapfrog Lenny | frog | hat=crown:f6c531 a=hops:10000 r=3",
      "Bounce Legend Bea | bunny | body=f6d06a back=cape:e84a8a fx=stars a=hops:25000 r=4",
    ] },

  { id: "coins", name: "Coin Keepers", emoji: "🪙",
    blurb: "Every coin counts. These ones count them.",
    chars: [
      "Penny Pincher | mouse | hat=cap:f6c531 a=coinsEarned:100 r=1",
      "Nickel Nick | cat | body=c8d0d8 a=coinsEarned:500 r=1",
      "Piggy Bank Pam | pig | body=f6c531 snout=d9a02a a=coinsEarned:1000 r=2",
      "Treasure Trove Tess | crab | body=f6c531 belly=f6e08a hat=pirate fx=glitter a=coinsEarned:2500 r=2",
      "Goldfinch Gilly | chick | body=f6c531 fx=sparkle a=coinsEarned:5000 r=3",
      "Coin King Cole | rooster | body=f6d06a tail=d9a02a hat=crown back=cape:d33a3a fx=glitter theme=stardust a=coinsEarned:10000 r=4",
      "Jackpot Jay | parrot | body=3a7ad9 wing=f6c531 a=runCoins:25 r=2",
      "Bullion Bunny | bunny | body=f6c531 inner=d9a02a a=runCoins:50 r=3",
    ] },

  { id: "daredevils", name: "Daredevils", emoji: "⚡",
    blurb: "Close calls, long rides and a lot of trains.",
    chars: [
      "Close Shave Cleo | cat | face=shades a=near:10 r=1",
      "Steelnerve Nelly | robot | body=9aa3ad face=shades a=near:50 r=2",
      "Daredevil Dash | chick | hat=helmet:d9412e back=cape:f6c531 a=near:200 r=3",
      "Log Roller Luka | bear | hat=beanie:d33a3a a=logs:50 r=1",
      "River Rafter Ren | frog | hat=helmet:f6922a a=logs:250 r=2",
      "Captain Driftwood | turtle | hat=pirate face=stache:6a4a2a a=logs:1000 r=3",
      "Signal Sparky | robot | body=d9412e accent=f6c531 a=rails:25 r=1",
      "Platform Percy | pony | hat=cap:2a3a5a a=rails:100 r=2",
      "Express Eddie | dog | hat=cap:d33a3a back=cape:2a3a5a face=goggles a=rails:500 r=3",
    ] },

  { id: "collectors", name: "Collectors' Circle", emoji: "📚",
    blurb: "For the ones who want to meet everybody.",
    chars: [
      "Curator Clucky | chicken | face=glasses neck=bowtie:3a7ad9 a=owned:25 r=1",
      "Archivist Owlbert | owl | face=glasses hat=grad a=owned:50 r=2",
      "Gallery Gideon | pony | hat=antlers face=monocle a=owned:100 r=2",
      "Grand Collector Gem | peacock | hat=crown fx=glitter a=owned:200 r=3",
      "Keeper of Crossings | dragon | body=f6d06a belly=fff4c0 wing=d9a02a hat=crown back=cape:8a5ad9 fx=glitter theme=stardust a=owned:300 r=4",
      "Lever Lottie | cat | hat=party:8a5ad9 a=pulls:10 r=2",
      "Gumball Gerty | blob | body=ff7ab0 mark=spots:ffffff hat=propeller a=pulls:50 r=3",
    ] },

  /* ======================================================= secrets (30) */

  { id: "hatchery", name: "Hidden Hatchery", emoji: "🥚",
    blurb: "Found by doing funny things on the road.",
    chars: [
      "Backwards Bertie | chicken | hat=cap:3a7ad9 s=moonwalk r=3",
      "Log Surfer Lars | penguin | face=shades neck=lei s=logSurfer r=3",
      "Thirteen Thistle | cat | body=2a2a30 inner=8a6aa0 hat=wizard:3a3a58 s=thirteen r=3",
      "Oopsy Daisy | chick | hat=bow:ff9ec4 face=blush s=oops r=3",
      "Arrow Archie | duck | hat=cap:d33a3a s=arrow r=3",
      "Frugal Fergus | frog | face=monocle s=penniless r=3",
      "Combo Cosmo | fish | body=f6c531 fin=d9a02a fx=sparkle s=coinCombo r=3",
      "Edge Explorer Esme | bunny | back=backpack:6a8a3a hat=bucket:6a8a3a s=bothSides r=3",
      "Tree Hugger Twig | bear | body=6a8a4a muzzle=b8c890 hat=sprout s=treeHugger r=3",
      "Bonk Bumblewick | sheep | hat=helmet:f6c531 s=wallBonk r=3",
      "Speedy Spud | mouse | back=cape:d33a3a face=goggles s=speedy r=3",
      "Stamina Stanley | dog | neck=medal hat=cap:ffffff s=marathon r=3",
      "Whisker Width Walter | cat | body=d8d8e0 face=goggles s=nearFive r=3",
      "Rail Dash Rory | pony | body=2a2a30 mane=d9412e s=railDash r=3",
      "Log Lover Loretta | bear | body=a8603a hat=bucket:6a8a3a s=logLover r=3",
    ] },

  { id: "oddities", name: "Curious Oddities", emoji: "🔮",
    blurb: "Nobody quite knows how these ones turn up.",
    chars: [
      "Pause Button Pippa | teapot | body=f4f0e8 accent=3a7ad9 s=pauseParty r=3",
      "Comeback Corky | rooster | back=cape:e84a4a s=comeback r=3",
      "Breezy | ghost | body=e0f4ff fx=feathers s=blownAway r=3",
      "Splashy McSplash | duck | body=6ab0e8 head=3a7ad9 fx=drops s=splashes r=3",
      "Triple Crown Tina | chicken | hat=crown mark=stars:f6c531 s=bestStreak r=3",
      "No-Coin Nora | fox | s=noCoinWin r=3",
      "Original Olive | chicken | body=fffaf0 hat=laurel s=loyal r=3",
      "Evening Evie | owl | body=6a5a8a disc=e0d0f0 s=evening theme=fireflies r=3",
      "Early Bird Ellis | rooster | body=f6d06a neck=scarf:f6922a s=earlyBird r=3",
      "Hello Hector | chick | fx=hearts s=heroTaps r=3",
      "Eggbert | chick | body=fffaf0 shell=ffffff s=eggSearch r=3",
      "Heartfelt Honey | bear | body=f4a0b8 muzzle=ffe0e8 mark=hearts:e84a8a s=favTen r=3",
      "Flip Flop Felix | blob | body=8ad0f0 mark=check:3a7ad9 s=viewFlip r=3",
      "Piggy Penny | pig | body=f6c531 snout=e8a02a face=blush s=zeroCoins r=3",
      "Scoreboard Scout | dog | hat=cap:3a7ad9 neck=medal s=scoreFan r=3",
    ] },

  /* ============================== annual events, back every year (20) */

  { id: "winter", name: "Winter Wonders", emoji: "⛄",
    blurb: "Christmas Crossing (December) and Snow Globe Days (late June to July).",
    chars: [
      "Jingle Hen | chicken | hat=santa neck=bell e=christmas:1 theme=snowfall r=3",
      "Tinsel Trotter | pony | body=a87a5a mane=f4f8ff hat=antlers neck=bell e=christmas:2 theme=snowfall r=3",
      "Gingerbread Gabe | person | skin=c8844a body=c8844a pants=c8844a form=bald neck=bowtie:e84a4a e=christmas:3 r=3",
      "Bauble Bot | robot | body=d9312e accent=f6c531 visor=2a2a30 hat=santa fx=glitter e=christmas:4 theme=snowfall r=4",
      "Snow Globe Sophie | penguin | hat=beanie:e84a8a fx=snow e=snowglobe:1 theme=snowfall r=3",
      "Cocoa Bear | bear | body=8a5a3c hat=beanie:ffffff neck=scarf:d33a3a e=snowglobe:2 theme=snowfall r=3",
      "Frost Fairy Faye | person | back=wings:c0f0ff body=c8e8ff form=bun hair=ffffff skin=f4d8c0 hat=tiara:8ad0f0 fx=snow e=snowglobe:3 theme=snowfall r=4",
    ] },

  { id: "spring", name: "Spring Fling", emoji: "🌷",
    blurb: "Friendship Fortnight (February), the Easter Egg Hunt and Blossom Weeks (September).",
    chars: [
      "Egg Hunter Elsie | bunny | back=backpack:f6c531 e=easter:1 r=3",
      "Cocoa Chick | chick | body=8a5a3a beak=f6c531 e=easter:2 r=3",
      "Speckled Egg Eli | blob | body=c8e8ff mark=speckle:8a5ad9 hat=ears:ffffff e=easter:3 theme=blossom r=4",
      "Cherry Blossom Bo | dove | body=ffd8e8 hat=flower:ff9ec4 fx=petals e=blossom:1 theme=blossom r=3",
      "Petal Pixie | person | back=wings:ffd0e8 body=ffb0d0 form=long hair=f4f0f8 fx=petals e=blossom:2 theme=blossom r=4",
      "Kindness Kai | dog | neck=lei:e84a8a fx=hearts e=friendship:1 r=3",
      "Huggable Holly | bear | body=ffb0c0 muzzle=fff0f0 mark=hearts:e84a8a fx=hearts e=friendship:2 r=4",
    ] },

  { id: "parties", name: "Party Calendar", emoji: "🎉",
    blurb: "The New Year Parade, the Pumpkin Patch (late October) and a Seaside Holiday (January).",
    chars: [
      "Firework Flick | chicken | hat=party:8a5ad9 fx=confetti e=newyear:1 r=3",
      "Countdown Clara | robot | body=2a2a40 accent=f6c531 hat=tophat:2a2a30 fx=confetti e=newyear:2 theme=neon r=4",
      "Jack O'Lantern Jo | fruit | body=f08a24 form=orange e=pumpkin:1 theme=autumn r=3",
      "Harvest Hedgehog | hedgehog | hat=straw:d9822b fx=leaves e=pumpkin:2 theme=autumn r=3",
      "Scarecrow Stitch | person | hat=straw:d9822b body=8a6a3a mark=check:6a4a2a pants=3a5a8a skin=f0d8a0 form=bald e=pumpkin:3 theme=autumn r=4",
      "Sandcastle Suki | crab | hat=bucket:f6c531 fx=drops e=seaside:1 theme=bubbles r=3",
    ] },
];

Roster.build(COLLECTIONS, PLANS);
